# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target '顶部放大' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

pod 'AFNetworking'
pod 'YYWebImage'

end
